"""Flight-independent SMPF geometry, memory, and planning contracts."""

from .contracts import CameraIntrinsics, DepthEstimate, ObjectSphere, ValidationIssue, ValidationResult
from .geometry import (
    body_from_color_transform,
    body_from_color_via_infra1,
    deproject_color_pixel,
    invert_rigid_transform,
    rigid_transform,
    robust_depth_estimate,
    rotation_matrix_from_quaternion,
    sphere_from_aligned_bbox,
    transform_points,
    validate_extrinsic_transform,
    validate_polyline,
)
from .deterministic_planner import (
    VisibilityGraphError,
    VisibilityGraphPlan,
    approach_goal_candidates_for_sphere,
    approach_goal_for_sphere,
    plan_visibility_graph,
)
from .goal_validation import GoalValidationResult, validate_goal_conditioned_polyline
from .follow_policy import (
    FOLLOW_CONTINUE,
    FOLLOW_SUCCESS,
    FOLLOW_TIMEOUT,
    FOLLOW_UNSAFE,
    FollowGoal,
    FollowGoalSelectionError,
    evaluate_follow_surface_standoff,
    next_follow_observation_is_final,
    select_follow_goal,
    validate_follow_goal_point,
)
from .yaw_policy import normalize_yaw, target_facing_yaws
from .obstacle_relevance import CorridorObstacleAssessment, assess_corridor_obstacles
from .execution import (
    ACTIVE_EXECUTION_STATES,
    ExecutionStateError,
    TERMINAL_EXECUTION_STATES,
    WaypointExecutionLoop,
)
from .artifacts import SmpfArtifactWriter, colorize_depth_image
from .experiment_log import JsonlExperimentLogger, redact_sensitive
from .model_defaults import (
    DEFAULT_LLM_MODEL,
    DEFAULT_LLM_REASONING_EFFORT,
    DEFAULT_VLM_MODEL,
    SUPPORTED_LLM_REASONING_EFFORTS,
    resolve_llm_reasoning_effort,
)
from .scene_memory import MemoryEntry, SemanticSceneMemory
from .target_identity import CompletedTargetError, TargetIdentityState, associate_target_observation
from .model_planner import (
    GuidepointPlan,
    DeterministicFallbackError,
    ModelPlannerClient,
    ModelPlannerError,
    ModelTransportError,
    PlanningRequest,
    PlanSchemaError,
    PlanValidationError,
    build_planning_prompt,
    parse_and_validate_plan,
)
from .sam_client import (
    DEFAULT_SAM_HOST,
    DEFAULT_SAM_PORT,
    SamClient,
    SamClientError,
    SamMask,
    SamPrediction,
    SamProtocolError,
    SamTransportError,
)
from .vision_detector import (
    Detection,
    DetectionSchemaError,
    DetectionTransportError,
    SceneDetection,
    VisionDetectorClient,
    VisionDetectorError,
    detection_prompt,
    parse_detection,
    parse_scene_detection,
    scene_detection_prompt,
)
from .task_stages import (
    TaskStage,
    TaskStageClient,
    TaskStageError,
    TaskStageSchemaError,
    TaskStageTransportError,
    TaskStages,
    parse_task_stages,
    task_stage_prompt,
)

__all__ = [
    "CameraIntrinsics",
    "ACTIVE_EXECUTION_STATES",
    "DepthEstimate",
    "Detection",
    "DetectionSchemaError",
    "DetectionTransportError",
    "SceneDetection",
    "ExecutionStateError",
    "DEFAULT_SAM_HOST",
    "DEFAULT_SAM_PORT",
    "ObjectSphere",
    "GuidepointPlan",
    "GoalValidationResult",
    "FOLLOW_CONTINUE",
    "FOLLOW_SUCCESS",
    "FOLLOW_TIMEOUT",
    "FOLLOW_UNSAFE",
    "FollowGoal",
    "FollowGoalSelectionError",
    "DeterministicFallbackError",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_LLM_REASONING_EFFORT",
    "DEFAULT_VLM_MODEL",
    "JsonlExperimentLogger",
    "SmpfArtifactWriter",
    "colorize_depth_image",
    "ModelPlannerClient",
    "ModelPlannerError",
    "ModelTransportError",
    "PlanningRequest",
    "PlanSchemaError",
    "PlanValidationError",
    "SamClient",
    "SamClientError",
    "SamMask",
    "SamPrediction",
    "SamProtocolError",
    "SamTransportError",
    "TERMINAL_EXECUTION_STATES",
    "TaskStage",
    "TaskStageClient",
    "TaskStageError",
    "TaskStageSchemaError",
    "TaskStageTransportError",
    "TaskStages",
    "MemoryEntry",
    "SemanticSceneMemory",
    "SUPPORTED_LLM_REASONING_EFFORTS",
    "CompletedTargetError",
    "CorridorObstacleAssessment",
    "TargetIdentityState",
    "associate_target_observation",
    "ValidationIssue",
    "ValidationResult",
    "VisionDetectorClient",
    "VisionDetectorError",
    "WaypointExecutionLoop",
    "VisibilityGraphError",
    "VisibilityGraphPlan",
    "approach_goal_candidates_for_sphere",
    "approach_goal_for_sphere",
    "assess_corridor_obstacles",
    "body_from_color_transform",
    "body_from_color_via_infra1",
    "build_planning_prompt",
    "deproject_color_pixel",
    "detection_prompt",
    "evaluate_follow_surface_standoff",
    "invert_rigid_transform",
    "parse_and_validate_plan",
    "parse_detection",
    "next_follow_observation_is_final",
    "normalize_yaw",
    "plan_visibility_graph",
    "parse_task_stages",
    "parse_scene_detection",
    "rigid_transform",
    "robust_depth_estimate",
    "rotation_matrix_from_quaternion",
    "scene_detection_prompt",
    "select_follow_goal",
    "resolve_llm_reasoning_effort",
    "redact_sensitive",
    "sphere_from_aligned_bbox",
    "transform_points",
    "validate_extrinsic_transform",
    "validate_goal_conditioned_polyline",
    "validate_follow_goal_point",
    "task_stage_prompt",
    "target_facing_yaws",
    "validate_polyline",
]
